### ISSUE TITLE
GraphiQL - GraphQL service detection

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/app-graphiql#8]
For now there is no way to give information about a service the way we do it for widgets with interfaces. 

A proposition of algorithm to generate a graphql URL would be the following.
```
For each site I can read
  For each application
    If a service "graphql" is present
      Generate URL
If none then generate dummy URL with 'mysite' as site and 'myapp' as app

Generate URL
  Check if site is published and if it is select master branch
  Concatenate URL and use portal.Url
```

**Comment by sigdestad** [comment]
What does this mean? 
If none then generate with 'mysite' as site and 'myapp' as app

**Comment by GlennRicaud** [comment]
Yes now I have this dummy generated URL that looks like this:
/admin/tool/com.enonic.app.graphiql/graphiql/_/service/com.enonic.app.myapp/graphql

I wanted to have something that tries to find a valid GraphQL URL until we have something better in service descriptors
